spring.application.name=meshPay
spring.datasource.url=jdbc:postgresql://localhost:5432/meshPay
spring.datasource.username=postgres
spring.datasource.password=sambhav@11052005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=MyVerySecretKeyForMeshPayApplicationThatShouldBeAtLeast32CharactersLong
jwt.expiration=86400000
spring.profiles.active=dev
